### ISSUE TITLE
Accept both tracking results and gold standard as file path 

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsscoring#1]
Here https://github.com/Sage-Bionetworks/neurolincsscoring/blob/master/exec/tracking_summary_perfect_tracks.R

For modularity and to plug in nicely to the challenge workflow template

**Comment by kdaily** [comment]
done, pushed to master.

![gasp](https://media.giphy.com/media/UZtyaSGyC9Wbm/giphy.gif)
