### ISSUE TITLE
Stdout output includes unnecessary info

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsscoring#2]
The output of `tracking_summary_perfect_tracks.R` looks like

```
Curated data has 29686 rows

Tracking submission has 11237 rows

[1] TRUE
Experiment,perfect tracks,total,percentage
LINCS092016B,762,927,0.8220064724919094
```

This is awkward to parse as a csv. I recommend writing results to a file so that we can be certain they are free of warnings or other noise.

Another issue involves pulling the stdout output from the docker container since we are wrapping the `docker` call in a python script within the neurolincsdreamchallenge workflow. If the output is in the form of a file I know I can mount the output directory before invoking `docker`.

**Comment by kdaily** [comment]
All messages go to `stderr` (except that errant `TRUE`, but I can fix that), so you can capture output of the data as such:

```Rscript exec/tracking_summary_perfect_tracks.R --tracking_file=syn12184077 --curated_data_table=syn18344955 1>/tmp/foo.csv```

**Comment by kdaily** [comment]
Fixed by https://github.com/Sage-Bionetworks/neurolincsscoring/commit/708df8f376aee12f7cd2fb77dea5bbdd43267038

**Comment by kdaily** [comment]
You should be able to fix (meaning, choose yourself) the name of the output file as part of the workflow. Then you can be assured of the existence of the output directory, just like:

https://github.com/Sage-Bionetworks/SynapseWorkflowExample/blob/master/sample-workflow.cwl#L20-L21

**Comment by philerooski** [comment]
Ah, I didn't know that stdout would be pushed to my local stdout if I'm using `os.system` to invoke the container.

**Comment by kdaily** [comment]
![hope](https://media.giphy.com/media/bIRFRUxcRG3Sw/giphy.gif)
